// Dropdown values extracted from the Job Planning Register Excel format.

export const CUSTOMER_NAME_OPTIONS = [
  "AB Jewellers",
  "ABB India Limited",
  "Afcons Infrastructure Limited",
  "Chiripal Industries Limited",
  "Collected ventures- flexone",
  "Dorf-Ketal Chemicals India Limited",
  "Drashta Green Power Limited",
  "Eiffil Water Infra Ltd.",
  "Elite Electricals",
  "Euphoria Packaging Private Limited",
  "Filatex India Limited",
  "Gujarat Credo Alumina Chemicals Ltd",
  "HEC Infra Projects Limited",
  "Hyosung T & D India Pvt. Ltd.",
  "Karamtara Engineering Limited",
  "L&T Construction",
  "LCC Engineering",
  "Linemark Crop Care",
  "Sterling and Wilson Pvt Ltd.",
  "Necessa Technologies",
  "Oswal Energies Ltd",
  "Pidilite Ind. Ltd.",
  "Prashanti Medical Services And Research Foundation",
  "Shapoorji Pallonji And Company Private Limited",
  "Shukun Ethanol Pvt. Ltd.",
  "SKAPS Industries India Pvt. Ltd.",
  "SNF Flopam India Pvt. Ltd.",
  "SNK Flex Private Limited",
  "Sri Sathya Sai Heart Hospital",
  "Tata Chemicals Ltd.",
  "Thermosag India Pvt. Ltd",
  "Torrent Power Ltd.",
  "Unison Pharmaceuticals Pvt. Ltd.",
  "Vikas Pandya - Sun Automac",
  "Vishakha Glass Pvt. Ltd.",
  "Vishal Fabrics Ltd",
  "Vocation",
  "Waystar Realty Private Limited"
].sort();



export const PANEL_NAME_OPTIONS = [
  "1000A TP+N ACB ISOLATOR PANEL",
  "11 Bus Side Earthing Truck",
  "11 KV Cable Side Earthing Truck",
  "11KV 630A OUTDOOR TYPE VCB PANEL (ICOG)",
  "11KV 800A HT ICOG PANEL",
  "11kV HT Panel-2",
  "11KV ICOG Panel",
  "11kV Indoor Panel",
  "11KV RMU Panel",
  "11KV VCB Panel",
  "11KW STAR-DELTA STARTER",
  "120KVAR RTPFC",
  "1250A TP+N ACB ISOLATOR PANEL",
  "125A TP+N MCCB ISOLATOR PANEL",
  "150kVAR APFC Panel",
  "15KVAR APFC Panel",
  "15KW STAR-DELTA STARTER",
  "15KW VFD Panel",
  "2.2KW DOL STARTER",
  "200KVAR Fix Capacitor Bank Panel",
  "220V DCDB",
  "24VAC Pullcord Box",
  "25 HP VFD Panel",
  "250A TP+N MCCB ISOLATOR PANEL",
  "250KVAR Fix Capacitor Bank Panel",
  "275KW VFD Panel",
  "3.7KW DOL STARTER",
  "300KVAR Fix Capacitor Bank Panel",
  "33 KV Bus Side Earthing Truck",
  "33 KV Cable Side Earthing Truck",
  "33KV HT Panel",
  "33KV VCB Panel",
  "37KW VFD Panel",
  "390KW VFD Panel",
  "400A JUNCTION BOX",
  "400A TP+N MCCB ISOLATOR PANEL",
  "400KVAR APFCR Panel",
  "415KW VFD Panel",
  "450KVAR RTFCR PANEL",
  "5.5KW DOL STARTER",
  "5000A ACB Extension Panel",
  "5000A Busduct",
  "6.6KV VCB Panel",
  "600 KVAR APFC PANEL",
  "630A ALU JUNCTION BOX",
  "630A TP+N MCCB ISOLATOR PANEL",
  "63A TP+N MCCB ISOLATOR PANEL",
  "7.5KW STAR-DELTA STARTER",
  "800A 11KV HT Outdoor Panel",
  "800A TP+N ACB ISOLATOR PANEL",
  "ACDB",
  "AHU Panel",
  "APFC Panel",
  "ARC LOAD LINE DISTRIBUTION BOARD",
  "AREA LIGHTING PANEL",
  "AUXILIARY DB",
  "Balling VFD Line Up Panel",
  "Benefication VFD Line Up Panel",
  "Breaker Handling trolley",
  "Burn Out MCC",
  "Cationic Spinning PCC",
  "COMMON AREA PANEL",
  "CONTROL DESK PANEL",
  "CONTROL PANELS FOR FANS",
  "CONTROL POST",
  "CPT DB PANEL",
  "DB For power point",
  "DCDB",
  "DISTRIUTION PANEL",
  "DWTT PANEL",
  "EDB Panel",
  "Electrical Panel",
  "ELP Panel",
  "ELV FLEXI TIER DB",
  "EMERGENCY LIGHTING PANEL",
  "EXTERNAL AREA LIGHTING PANEL",
  "Extruder MCC",
  "FIRST BASEMENT STACK PARKING PANEL",
  "FIRST FLOOR PANEL",
  "Flexone_GF LT Meter panel",
  "GROUND FLOOR LIGHTING & POWER PANEL",
  "GROUND FLOOR METER PANEL",
  "HTM MCC",
  "IMCC Cum VFD Panel",
  "Junction box for EMS System",
  "LDB",
  "LED JB",
  "LIFT PANEL",
  "Lighting Panel",
  "LINE ARC LOAD DISTRIBUTION BOARD",
  "LINE PANEL",
  "LRP DB",
  "LT Panel",
  "LT PCC Panel",
  "MAIN COMMON AREA LIGHTING & POWER PANEL",
  "Main Distribution panel",
  "Main LT Panel",
  "MAIN PANEL",
  "MAIN PCC PANEL (TTA)",
  "MCC Panel",
  "MCC Cum VFD Panel",
  "METER PANEL",
  "MLDB",
  "Outdoor PDB Panel",
  "PCC PANEL",
  "PDB PANEL",
  "PLANT ROOM PANEL",
  "PLUMBING PANEL",
  "PMCC Panel",
  "PRP panel",
  "RTDB Conveyor Panel",
  "SKIP FLOOR LIGHTING & POWER PANEL",
  "SLDB",
  "SOLAR MAIN LT PANEL",
  "Spin Finish Oil MCC",
  "SUB DISTRIBUTION PANEL",
  "Sub Station PDB Panel",
  "Sub-MLDB",
  "Sub-PRP",
  "TERRACE EQUIPMENT PANEL",
  "TGD VFD Line Up Panel",
  "UPS PANEL",
  "Utility MCC Panel"
].sort();

export const INDUSTRY_OPTIONS = [
  "Beverages",
  "Chemicals",
  "Construction & Real Estate",
  "Engineering",
  "Fabrics & Textiles",
  "Healthcare",
  "Jewellery",
  "Manufacturing",
  "Packaging",
  "Paint",
  "Pharmaceuticals",
  "Power Generation",
  "Solar",
  "Steel",
  "Water"
].sort();

export const PANEL_TYPE_OPTIONS = [
  "11KV HT",
  "33KV HT",
  "800V",
  "ABB Ar-tu-k",
  "IMCC (Non TTA)",
  "Non TTA",
  "SS316",
  "TTA",
  "TTA and Non-TTA"
].sort();

