const { EXCEL_DEPARTMENTS, EXCEL_FIELD_DEFS } = require("./excelFormat");

const DEFAULT_DEPARTMENTS = EXCEL_DEPARTMENTS;
const DEFAULT_FIELD_DEFS = EXCEL_FIELD_DEFS;

module.exports = {
  DEFAULT_DEPARTMENTS,
  DEFAULT_FIELD_DEFS,
};
